### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by Jiaxinliu-cindy** [smcdermott3/project#2]
I love the design consistency of your webpage. 
Something for you to consider:
- the icon of sitemap is really small, and a little hard to find. 
- without reading your code, I wouldn't know that button next to site map is a dark mode button
- for dark mode, here is something that might be helpful:
https://www.w3schools.com/howto/howto_js_toggle_dark_mode.asp

**Comment by smcdermott3** [comment]
Thanks for the feedback on the button visibility. I'll add some tweaks. to make it stand out more and be more clear.

I've used that site as a foundation, but all the CSS needs to be internal. I'll keep trying but hopefully the button will also be more clear with functionality.
