### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by ctoledo1** [smcdermott3/project#4]
Your webpage is beyond impressive! You did an amazing job :) 

>Bugs: 
1.The playlist page is showing a warning.
2.The map on the contact page is taking space over the comments bar. I would suggest making it smaller or taking it out. Don't think it is really relevant to your webpage. 

>Content: 
1.If you are down, it would be nice if you could add a picture of yourself in the contact page. If you have one in a concert would be cool as it shows your passionn for music.
2.I would put First name before last name in the contact page.

**Comment by smcdermott3** [comment]
Thank you for the feedback! 

The warning page is meant to show up before entering the playlist page, but everything else was great feedback and has been taken care of.

Thank you
